#include "c4d.h"
#include "dummyplugin.h"

Bool DummyPlugin::Execute(BaseDocument* doc)
{
	if (nullptr == doc)
		return false;

	const String activeDocName = doc->GetDocumentName().GetFileString();
	GePrint("This is a new string generated by the DummyPlugin whilst "+activeDocName+" document is active.");

	return true;
	
}